### ISSUE TITLE
error about 'make external'

### ISSUE THREAD

**Issue by make-j4** [msoeken/cirkit#34] opened 2017-07-10 09:16 UTC
I get the following error on running make external.
@msoeken Kindly help me

**Comment by msoeken** [comment] 2017-07-10 09:18
There is no error described in your text.

**Comment by make-j4** [comment] 2017-07-10 09:25
![2017-07-10 17-23-59](https://user-images.githubusercontent.com/30041885/28011401-c413ee2e-6594-11e7-937d-3dcdfcb7a6b5.png)

**Comment by msoeken** [comment] 2017-07-10 09:27
There is a log file mentioned in the error description, `cryptominisat-build-*.log`. Can you please attach this file.

**Comment by make-j4** [comment] 2017-07-10 09:29
File "setup.py", line 86
SyntaxError: Non-ASCII character '\xe6' in file setup.py on line 86, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
make[6]: *** [pycryptosat/build/timestamp] Error 1
make[5]: *** [pycryptosat/CMakeFiles/python_interface.dir/all] Error 2
make[4]: *** [all] Error 2

**Comment by msoeken** [comment] 2017-07-10 09:31
Need to look into this one. Can you send me your Python version and Ubuntu version.

**Comment by make-j4** [comment] 2017-07-10 09:33
Python 3.5.2
ubunbu 16.04

**Comment by make-j4** [comment] 2017-07-10 09:38
Why can't I also build all the previous versions of revkit?

**Comment by make-j4** [comment] 2017-07-10 10:02
There is a error when build RevKit-2.2 

[cudd-build-err.txt](https://github.com/msoeken/cirkit/files/1135102/cudd-build-err.txt)

**Comment by msoeken** [comment] 2017-07-10 11:54
RevKit 2.2 is not any longer maintained. The versions of the tools are important, not the version of the distribution.

**Comment by make-j4** [comment] 2017-07-12 04:35
file:///home/dr/Pictures/Screenshot%20from%202017-07-12%2004:29:12.png
I had installed all the mentioned packages in the readme. I'am hopeless. what I should do?  @msoeken Kindly help me.

**Comment by msoeken** [comment] 2017-07-12 09:05
Can you please update and check whether problem is resolved?

**Comment by make-j4** [comment] 2017-07-13 00:33
dr@dr-SMBIOS-606:~/Downloads/git-2.8.0$ git --version
git version 2.8.0
There is the same error

**Comment by msoeken** [comment] 2017-07-13 04:53
I removed the cryptominisat dependency in 4c84df2. The same error as mentioned in the first post can no longer exist. I suggest to start from scratch and clone the repository again.

**Comment by make-j4** [comment] 2017-07-13 08:48
Thank you very much, wo try it again.

**Comment by make-j4** [comment] 2017-07-13 08:50
Thank you very much, I try it again.

**Comment by make-j4** [comment] 2017-07-13 08:51
Thank you very much, I will try it again.

**Comment by make-j4** [comment] 2017-07-13 09:16
what's  the mean of "clone the repository again"?

**Comment by msoeken** [comment] 2017-07-13 09:19
Please check the following resources:

https://github.com/msoeken/cirkit#build-and-run-cirkit

https://try.github.io/levels/1/challenges/1

**Comment by make-j4** [comment] 2017-07-15 00:21
![cmake](https://user-images.githubusercontent.com/30041885/28234799-711dc08c-6936-11e7-8676-c7161bd6b0cd.png)
![make cirkit3](https://user-images.githubusercontent.com/30041885/28234804-7c5f79f4-6936-11e7-9070-f9b68b232700.png)
[abc-build-err.txt](https://github.com/msoeken/cirkit/files/1149915/abc-build-err.txt)

I did start from scratch and clone the repository again.  'cmake ..' and 'make external' are running fine but 'make cirkit' is not working.

**Comment by make-j4** [comment] 2017-07-15 00:26
I executed the following commands to install Boost ,
./utils/tools.py install boost
cmake -DBoost_NO_SYSTEM_PATHS=TRUE -DBOOST_ROOT:PATHNAME=`pwd`/tools/boost_1_63_0/ ..
export CIRKIT_HOME=/home/dr/下载/cirkit
export LD_LIBRARY_PATH=$CIRKIT_HOME/ext/lib:$LD_LIBRARY_PATH

**Comment by msoeken** [comment] 2017-07-15 09:01
Should be fixed in 4635a79. Can you update and check please?

**Comment by make-j4** [comment] 2017-07-15 13:16
Thanks a lot for what you've done for me! 
I'll do it again

**Comment by make-j4** [comment] 2017-07-15 16:24
![make cirkit3](https://user-images.githubusercontent.com/30041885/28240890-0893e16e-69bc-11e7-8ca5-6b1b51701ba6.png)

In the post, “错误” is mean of 'error ', "未定义的引用" is mean of 'undefined reference to'

**Comment by make-j4** [comment] 2017-07-17 00:33
However I also did start from scratch and clone the repository on a another computer with the same distribution and tools, but now I get the same error as the one S-Dutta1 got.
![make external](https://user-images.githubusercontent.com/30041885/28252683-8bbcae18-6aca-11e7-8a03-e59df704a4ff.png)

**Comment by msoeken** [comment] 2017-07-17 05:37
Can you please attach the log file that is mentioned together with the error.

**Comment by make-j4** [comment] 2017-07-17 06:59
I have updated two comments above with the log files.

**Comment by msoeken** [comment] 2017-07-17 07:34
I am really not sure what's going on here. Somehow the installation seems broken. I don't understand why there is a ABC_NAMESPACE_HEADER_START symbol in the file zconf.h when install MiniSAT. I won't be able to reproduce this error.

**Comment by make-j4** [comment] 2017-07-17 07:52
the error in the first post is changing when I do it again

**Comment by make-j4** [comment] 2017-07-17 08:21
[abc-build-err.txt](https://github.com/msoeken/cirkit/files/1151927/abc-build-err.txt)
[cudd-build-err.txt](https://github.com/msoeken/cirkit/files/1151928/cudd-build-err.txt)
![make cirkit3](https://user-images.githubusercontent.com/30041885/28260008-b7919f62-6b0b-11e7-9f6f-2bc07c958aeb.png)
why “50%” is stable？

**Comment by make-j4** [comment] 2017-07-17 08:42
I think it's impossible for me to build cirkit and revkit successfully. Could you send two executable files to me if they still can run correctly?

**Comment by make-j4** [comment] 2017-07-31 03:57
msoeken， please help me!
I'm stucked in the following error
![makerevkit](https://user-images.githubusercontent.com/30041885/28762230-539f21e6-75e7-11e7-8d11-affc8f247ad8.png)
[abc-build-err.txt](https://github.com/msoeken/cirkit/files/1186359/abc-build-err.txt)

**Comment by choforito84** [comment] 2017-08-10 17:26
If that problem appears when executing the `make external` command of the installation process, have you tried to continue the installation and run the `make revkit` command? It may still build Revkit, and it appears that the problem is due to ABC compatibility.

**Comment by make-j4** [comment] 2017-08-12 03:49
@choforito84 , The  command of 'make external'  was successfully installed. That problem appears when executing the 'make revkit'. How can I resolve this ABC compatibility problem?

**Comment by choforito84** [comment] 2017-08-14 23:50
Make sure you do not have a Cache for compilation, such as Ccache or similar programs. Could I get a list of the version of you dependencies (Boost, GCC, Cmake and Make)?

**Comment by make-j4** [comment] 2017-08-15 01:37
@choforito84 , My dependencies are as follows 
Boost version: 1.63.0
gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
cmake version 3.8.2
GNU Make 3.81

**Comment by choforito84** [comment] 2017-08-16 16:32
Your GNU make version is fairly old. Could you update it and try to see if there is any improvement. Please erase the whole content of your `build` directory also to make a clean install.

**Comment by make-j4** [comment] 2017-08-17 03:48
@msoeken
when make external, the following error occurred：
         error: downloading 'http://msoeken.github.io/tools/minisat-2.2.0-clang.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
Why?

**Comment by choforito84** [comment] 2017-08-17 17:02
That seems like a problem of your internet conection. I can clic on the link and the download works for me. Are you working with a reliable internet conection?

**Comment by make-j4** [comment] 2017-08-18 02:07
@choforito84, Last time I could browse the web page, but I couldn't clic on the link and the download works.   Just take your advice and I can do it.   I updated the version of make (GNU make 4.2.1)and now make it again. I'll give you feedback. Thank you very much!

**Comment by make-j4** [comment] 2017-08-18 02:14
The same mistake still exists. @choforito84, why? How to do?

**Comment by choforito84** [comment] 2017-08-18 20:07
The log file is full of warnings of ABC, but I can't see an error. If you try to install ABC in your computer as a standalone, you might get a better idea of the installation problems. The ABC repository, along with its installation procedure, can be found [here](https://bitbucket.org/alanmi/abc)

**Comment by make-j4** [comment] 2017-08-20 02:13
@choforito84,  I replaced my "libabc.a" as Alan Mishchenko's libabc.a, It appear more "undefined reference to".  I guess it's a install question of abc.  So can you copy one for me and I want to try your "libabc.a". my email: 289132337@qq.com 
![2017-08-20 10 11 55 make cirkit](https://user-images.githubusercontent.com/30041885/29491493-ff5cb716-858f-11e7-93c7-95242f806421.png)

In the post, “错误” is mean of 'error ', "未定义的引用" is mean of 'undefined reference to'

Thank you very much!

**Comment by msoeken** [comment] 2017-12-31 14:12
I have changed how dependencies are build recently. Those bugs should now be resolved.

**Closed by msoeken** 2017-12-31 14:12 UTC
